const { BASE_URL } = require('../constants');

const createPaymentLink = (z, bundle) => {
  const options = {
    url: `${BASE_URL}/${bundle.authData.environment}/payment-links`,
    method: 'POST',
    body: {
      amount: bundle.inputData.amount,
      payerId: bundle.inputData.payerId,
      description: bundle.inputData.description,
      currency: bundle.inputData.currency,
      linkExpiryDate: bundle.inputData.linkExpiryDate,
      allowedPaymentMethods: bundle.inputData.allowedPaymentMethods,
      surchargePaymentMethods: bundle.inputData.surchargePaymentMethods,
      returnUrl: bundle.inputData.returnUrl,
      metadata: bundle.inputData.metadata,
    },
  };

  return z.request(options).then((response) => {
    response.throwForStatus();
    return response.data;
  });
};

module.exports = {
  operation: {
    perform: createPaymentLink,
    inputFields: [
      {
        key: 'amount',
        label: 'Amount',
        type: 'integer',
        helpText: 'The amount to be paid through the Payment link (in cents).',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'payerId',
        label: 'Payer Id',
        type: 'string',
        helpText: 'Id of a Payer to create a Payment link for (e.g., `pyr_XXXXXXXXXXXXXX`).',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'description',
        label: 'Description',
        type: 'string',
        helpText: 'The description of the payment, shown on the payment page.',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'currency',
        label: 'Currency',
        type: 'string',
        helpText: 'Currency to take payment in (defaults to Merchant currency if not specified).',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'linkExpiryDate',
        label: 'Link Expiry Date',
        type: 'datetime',
        helpText: 'DateTime for the Payment Link to expire.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'allowedPaymentMethods',
        label: 'Allowed Payment Methods',
        type: 'string',
        helpText: 'List of Payment Methods that can be used to take Payment.',
        required: true,
        list: true,
        choices: ['credit-card', 'bank-account'],
        altersDynamicFields: false,
      },
      {
        key: 'surchargePaymentMethods',
        label: 'Surcharge Payment Methods',
        type: 'string',
        helpText: 'Payment methods that a surcharge should be applied to when used.',
        required: false,
        list: true,
        choices: ['credit-card', 'bank-account'],
        altersDynamicFields: false,
      },
      {
        key: 'returnUrl',
        label: 'Return URL',
        type: 'string',
        helpText: 'URL to redirect the user to once the payment has been completed.',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'metadata',
        label: 'Metadata',
        type: 'string',
        helpText: 'Free text field to store state against the Payment Link object.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      id: 'plk_XXXXXXXXXXXXXX',
      merchantId: 'mch_XXXXXXXXXXXXXX',
      amountInCents: 1200,
      currency: 'AUD',
      linkExpiryDate: null,
      description: 'Sample payment',
      url: 'https://pay.getpinch.com.au/pay/plk_XXXXXXXXXXXXXX',
      returnUrl: 'https://example.com/',
      metadata: null,
      surchargePaymentMethods: [],
      allowedPaymentMethods: ['credit-card'],
      payer: {
        id: 'pyr_XXXXXXXXXXXXXX',
        firstName: 'John',
        lastName: 'Smith',
        companyName: null,
        email: 'test@test.com',
      },
      payments: [],
    },
    outputFields: [
      { key: 'id', type: 'string' },
      { key: 'merchantId', type: 'string' },
      { key: 'amountInCents', type: 'number' },
      { key: 'currency', type: 'string' },
      { key: 'linkExpiryDate', type: 'datetime' },
      { key: 'description', type: 'string' },
      { key: 'url', type: 'string' },
      { key: 'returnUrl', type: 'string' },
      { key: 'metadata', type: 'string' },
      { key: 'surchargePaymentMethods', type: 'string', list: true },
      { key: 'allowedPaymentMethods', type: 'string', list: true },
      { key: 'payer__id', label: 'Payer Id', type: 'string' },
      { key: 'payer__firstName', label: 'Payer First Name', type: 'string' },
      { key: 'payer__lastName', label: 'Payer Last Name', type: 'string' },
      { key: 'payer__companyName', label: 'Payer Company Name', type: 'string' },
      { key: 'payer__email', label: 'Payer Email', type: 'string' },
      { key: 'payments[]id', label: 'Payment Id', type: 'string' },
      { key: 'payments[]status', label: 'Payment Status', type: 'string' },
    ],
  },
  key: 'payment_link_create',
  noun: 'Payment Link',
  display: {
    label: 'Create Payment Link',
    description: 'Creates a new payment link for a payer.',
  },
};
