'use strict';

const PaymentSample = {
    id: 'pmt_XXXXXXXXXXXXXX',
    attemptId: 'att_XXXXXXXX',
    amount: 1000,
    currency: 'AUD',
    description: '',
    applicationFee: 0,
    totalFee: 55,
    isSurcharged: false,
    sourceType: 'credit-card',
    transactionDate: '2021-04-26T07:15:52Z',
    status: 'approved',
    estimatedTransferDate: '2021-04-29',
    actualTransferDate: null,
    payer: {
      id: 'pyr_XXXXXXXXXXXXXX',
      firstName: '',
      lastName: '',
      emailAddress: '',
      mobileNumber: '',
      streetAddress: null,
      suburb: null,
      postcode: null,
      state: null,
      country: null,
      companyName: null,
      companyRegistrationNumber: null,
      metadata: null,
    },
    subscription: null,
    attempts: [
      {
        id: 'att_XXXXXXXX',
        amount: 1000,
        currency: 'AUD',
        convertedAmount: null,
        conversionRate: null,
        convertedCurrency: null,
        estimatedSettlementDate: '2021-04-29T00:00:00Z',
        isSurcharged: false,
        transactionDate: '2021-04-26T07:15:52Z',
        estimatedTransferDate: '2021-04-29',
        actualTransferDate: null,
        source: {
          id: 'src_XXXXXXXXXXXXXX',
          sourceType: 'credit-card',
          bankAccountNumber: null,
          bankAccountBsb: null,
          bankAccountName: null,
          creditCardToken: 'tkn_XXXXX',
          cardHolderName: '',
          expiryDate: '2022-12-01T00:00:00Z',
          displayCardNumber: '4242',
          cardScheme: 'visa',
          origin: 'AU',
          funding: 'credit',
        },
        dishonour: null,
        settlement: null,
        fees: {
          transactionFee: 55,
          applicationFee: 0,
          totalFee: 55,
          currency: 'AUD',
          taxRate: 0.1,
          convertedTransactionFee: null,
          convertedApplicationFee: null,
          convertedTotalFee: null,
          convertedCurrency: null,
          conversionRate: null,
        },
        status: 'approved',
      },
    ],
    metadata: null,
};


const PaymentOutputFields = [
  { key: 'id' },
  { key: 'attemptId' },
  { key: 'amount' },
  { key: 'currency' },
  { key: 'description' },
  { key: 'applicationFee' },
  { key: 'totalFee' },
  { key: 'isSurcharged' },
  { key: 'sourceType' },
  { key: 'transactionDate' },
  { key: 'status' },
  { key: 'estimatedTransferDate' },
  { key: 'actualTransferDate' },
  { key: 'payer__id' },
  { key: 'payer__firstName' },
  { key: 'payer__lastName' },
  { key: 'payer__emailAddress' },
  { key: 'payer__mobileNumber' },
  { key: 'payer__streetAddress' },
  { key: 'payer__suburb' },
  { key: 'payer__postcode' },
  { key: 'payer__state' },
  { key: 'payer__country' },
  { key: 'payer__companyName' },
  { key: 'payer__companyRegistrationNumber' },
  { key: 'payer__metadata' },
  { key: 'subscription' },
  { key: 'attempts[]id' },
  { key: 'attempts[]amount' },
  { key: 'attempts[]currency' },
  { key: 'attempts[]convertedAmount' },
  { key: 'attempts[]conversionRate' },
  { key: 'attempts[]convertedCurrency' },
  { key: 'attempts[]estimatedSettlementDate' },
  { key: 'attempts[]isSurcharged' },
  { key: 'attempts[]transactionDate' },
  { key: 'attempts[]estimatedTransferDate' },
  { key: 'attempts[]actualTransferDate' },
  { key: 'attempts[]source__id' },
  { key: 'attempts[]source__sourceType' },
  { key: 'attempts[]source__bankAccountNumber' },
  { key: 'attempts[]source__bankAccountBsb' },
  { key: 'attempts[]source__bankAccountName' },
  { key: 'attempts[]source__creditCardToken' },
  { key: 'attempts[]source__cardHolderName' },
  { key: 'attempts[]source__expiryDate' },
  { key: 'attempts[]source__displayCardNumber' },
  { key: 'attempts[]source__cardScheme' },
  { key: 'attempts[]source__origin' },
  { key: 'attempts[]source__funding' },
  { key: 'attempts[]dishonour' },
  { key: 'attempts[]settlement' },
  { key: 'attempts[]fees__transactionFee' },
  { key: 'attempts[]fees__applicationFee' },
  { key: 'attempts[]fees__totalFee' },
  { key: 'attempts[]fees__currency' },
  { key: 'attempts[]fees__taxRate' },
  { key: 'attempts[]fees__convertedTransactionFee' },
  { key: 'attempts[]fees__convertedApplicationFee' },
  { key: 'attempts[]fees__convertedTotalFee' },
  { key: 'attempts[]fees__convertedCurrency' },
  { key: 'attempts[]fees__conversionRate' },
  { key: 'attempts[]status' },
  { key: 'metadata' },
];

module.exports = {
    PaymentSample,
    PaymentOutputFields
};
