  
name: CI

on:
  push:
    branches-ignore:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci

    - name: Run Zapier Tests
      env:
        ENVIRONMENT: test
        MERCHANT_ID:  ${{ secrets.MERCHANT_ID }}
        SECRET_KEY:  ${{ secrets.SECRET_KEY }}
      run: npm run zapier:test