  
name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CI: ""
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - run: npm ci

    - name: Run Zapier Tests
      env:
        ENVIRONMENT: test
        MERCHANT_ID:  ${{ secrets.MERCHANT_ID }}
        SECRET_KEY:  ${{ secrets.SECRET_KEY }}
      run: npm run zapier:test