  
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install npm
      run: npm ci
    
    - name: Install Zapier CLI
      run: npm install -g zapier-platform-cli

    - name: Deploy App
      env:
        ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}
      run: zapier push