  
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CI: ""

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Install npm
      run: npm ci
    
    - name: Install Zapier CLI
      run: npm install -g zapier-platform-cli

    - name: Run Zapier Tests
      env:
        ENVIRONMENT: test
        MERCHANT_ID:  ${{ secrets.MERCHANT_ID }}
        SECRET_KEY:  ${{ secrets.SECRET_KEY }}
      run: npm run zapier:test

    - name: Deploy to Zapier
      env:
        ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}
      run: zapier push